---
title: "국제학교 외국인학교 출판 관련"
author: "PhilDoc"
---
  
```{r global_options, include=FALSE}
library(tufte)
library(knitr)
library(dplyr)
library(xlsx)

opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/', echo=FALSE, warning=FALSE, message=FALSE)
```

{frontmatter}

{body}
# Chapter 1. 국제학교와 외국인학교
가장 중요한 것은 국제학교와 외국인학교의 차이를 아는 것입니다.

# Chapter 2. 국제학교 총정리

## 제주국제학교 비교해보았습니다.

제주영어교육도시(Jeju Global Education City)는 제주특별자치도 서귀포시 대정읍 구억리 일대에 생활과 교육을 영어로 하는 정주형 영어교육도시의 이름입니다. 제주국제자유도시개발센터(JDC)가 추진하는 핵심 프로젝트 중 하나이지요.

현재 3개가 개교했고, 2017년에 1개 학교가 더 들어설 예정입니다.

가장 큰 차이점은 각자가 따르는 학제입니다.

NLCS는 영국, 브랭썸홀은 캐나다, KIS는 미국 학제를 각각 따릅니다. 이것이 가장 큰 고려 요소가 아닐까 싶습니다. 영국, 캐나다, 미국 학제 모두 세계를 선도하는 교육제도이기에 단순 비교는 힘들 듯 합니다. 우열을 가릴 수도 없겠지요.. 다만 선생님들의 출신국가, 억양, 현지 방문기회 등을 결정짓는 중요한 요소 중에 하나임은 틀림 없겠지요?

국제학교를 영어학습을 위해서 생각한다면 세 학교간 차이는 별로 없을 것 같습니다. 엄격한 quality control로 양질의 교육 수준을 유지하고 있다고 생각됩니다. (물론 세학교 모두를 다녀본 사람은 단언코 없기 때문에 직접적인 비교는 힘들듯 합니다.)

좀더 구체적으로 들어가보면 면적 비교해보면 NLCS > 브랭썸홀 > KIS이겠습니다. 학생수도 같은 순위겠고요..

자, 이제 각자의 본토 모교를 살펴보겠습니다.. 본토 모교로 방문하여 수학할 수 있는 기회가 있기 때문에 이것도 알아두시면 좋을 것 같습니다.
NLCS는 영국 런던의 정통 여학교이고요, 150년의 긴 전통 있는 학교입니다. 영국 Financial Times 발표 IB School 영국 순위 6년 연속 1위 ('06~'11)이고 매년 졸업생의 40% 이상 Oxford와 Cambridge대학 입학한다고 하네요. (단순 비교는 힘들지만 서울의 한 고등학교에서 40%가 서울대가는 것 이상으로 보시면 되겠습니다.)
브랭썸홀은 캐나다 토론토의 여학교이고, 역시 110년의 긴 전통 있는 학교입니다. 캐나다 최고 여자 명문 사립학교이고, 13년 세계 TOP Boarding Schools for Asian Students 선정,13년 캐나다 Top 25 Private Schools 선정되었습니다.
특징적으로 이 두학교의 본토 모교는 모두 여학교네요.
KIS는 본토 모교는 당연히 없겠지요.. 다만 교환학생 프로그램으로 미국에 있는 학교에 갈 수 있다고 들었습니다. (어느 주에 있는 어떤 수준의 학교인지는 확인을 해봐야 알 것 같습니다.)

대학 진학 수준은 아직 정확한 비교자료를 찾을 수 없네요.

NLCS, KIS는 전학년 남녀공학이고요, 브랭썸홀은 Year 4부터는 여학생만 공부할 수 있습니다. 아무래도 자유로운 분위기는 NLCS, KIS에서 형성이 될테고, 브랭썸홀은 여학생 위주의 비교적 차분한 분위기가 연출되지 않을까하는 생각을 해봅니다. 딸 가진 부모님은 이점도 고려해 볼 수 있을 것 같습니다.

정리해보자면, 영국, 캐나다, 미국 학제 중 어느것을 선택해야 할지.. 학교의 면적(자연환경) 및 방문기회 면에서 어디가 좋을지.. 남녀공학 여부 등이 고려사항이 될 수 있을 것 같습니다.

http://jdcenter.com/doc/sub2/sub242.jsp 여기에 가시면 좀더 많은 정보 얻으실 수 있습니다.




2016년에 개교하는 St. Johnsbury Academy는 대지면적도 NLCS수준으로 넓고, 미국식 학제에, 남녀공학이네요~
아직 개교 안했지만 참고로 알아두세요. ^^

본토 모교의 정보는 다음과 같습니다.



어마어마 하군요.. Coolidge 대통령이 여기 출신이라니..미국에 기반을 둔 높은 교육 수준으로 제주국제학교의 새로운 강자가 되지 않을까 생각합니다~ 무엇보다 Vermont는 동부 뉴잉글랜드 지역에 위치한 주로 제가 가보진 못했지만.. 그쪽 출신의 동료에게 미국에서 가장 아름다운 주 중에 하나라는 얘기를 귀따갑도록 들었던 곳인데요..한국엔 많이 알려진 곳은 아니지만 정말 좋다고 하더라구요~~

더 궁금한 점 있으시면 댓글 달아주세요

# Chapter 3. 외국인학교 총정리
외국인학교의 가장 큰 장점은 수도권에서 교육 시킬 수 있다는 것입니다.



# Chapter 4. 나의 자녀에게 맞는 학교 선정법

# Chapter 5. 원서 작성 예시 및 서류 전형 준비

# Chapter 6. 필기 시험

# Chapter 7. 면접 시험
uㄴ접만크
면접만큼 
- 저학년에서 특히 중요. 
- 그러나 모든 학년에서 마지막 관문으로 가장 중요함. 
여기엔 복붙......

# Chapter 8. 국제학교 입학 후 전략

# Chapter 9. 국제학교/외국인학교 용어정리

# Chapter 10. 합격 수기

# Selected Admission Posting
ㅗ


{backmatter}
# 원칙

* 존대말로
* Leanpub에 publication
*

2016년 8월에 입학하기 위하여 교복사야하는데
7월 4일~5일 대치동 은마상가에서 구입가능했으나 너무 복잡하여 제주에서 구입함

스쿨룩스 제주 광양점 064 724 5948



[DIS] 대구국제학교 동영상	|	대구국제학교소식
2016.07.21. 20:56	|	수정	|	삭제
PhilDoc(wrec****)
부 매니저
http://cafe.naver.com/assarabia/10766  
대구국제학교(DIS)는 상대적으로 덜 알려져 있지만, 최근 관심이 급증하고 있는 학교입니다.

경상도 및 충청도 지역 분들에게는 송도나 제주보다 접근성이 월등히 좋고, 무엇보다 학비가 상대적으로 낮습니다. (G1 기준 2100만원)

또한 앞선 몇몇 기사에서 보셨듯이 학교에서 academic outcome도 좋게 나오고 있습니다.

학교의 모습을 엿볼 수 있는 동영상 몇개를 첨부합니다. 선입견을 버리고 평가해보세요. 

다들 아시는 내용이겠지만, 대구국제학교는 국내학력이 인정되고 내국인의 경우 정원대비 30%까지 제약없이 입학가능하며, 현재 비교적 내국인 정원에 여유가 있는 것으로 알고 있습니다.

PhilDoc


I>

A>

Q>
