# IB School에서 국내대학(SKY) 진학시 참고해야 할 사항

## Introduction

- IB School에서 국내 대학 진학하시는 분들이 점점 늘고 있습니다. 
- 국제학교는 해외 유수의 대학을 진학할 수 있는 기회가 활짝 열려 있기 때문에 아직 국내 대학 진학에 대한 정보가 많지 않은 실정입니다. 
- 국내 명문대학 입시는 학업성취도가 매우 뛰어나면서도 다방면에 뛰어난 글로벌 인재를 받아들이는 쪽으로 향하고 있기에 일반공립학교에서 진학하기 점점 어려워지고 있는 실정입니다.
- 국제학교가 새로운 해법을 제시할 수도 있다는 생각을 해봅니다. 
- 아래는 island9님께서 올려주신 좋은 정보입니다. 정리해서 올려봅니다. <http://cafe.naver.com/assarabia/9635>

## Information

> 서울대 입학처에 문의 할것이 있어 전화 상담을 했습니다. IB DP 과정 공부한다면 자체가 워나 공신력 있고 힘든 교육인것 대학이 잘 아니 SAT 준비 하지 말라고 하네요. SAT 준비 할 시간에 dp 더 열심히 하는게 좋다고 합니다. 혹 국제 학교 보내면서 한국 대학 관심 있으신분 참고 하세요.

## Response
 
- Reply-1: 감사합니다. 얼마전 연세대 입학 설명회에서도 같은 말을 들었네요. IB 학교면 IB 점수가 제일 중요하니 괜히 다른거에 시간, 돈 낭비하지 말라고
- Reply-2: 저희 딸은 G1부터 IB 하는 해외에 소재 국제학교에서 공부 했어요.,라이팅이 실력이 중요하고,특히 dp는 배우 힘들기 때문에 그과정을 잘 이수한 학생이 대학에들어 온 후,공부를 잘 해서높이 평가 하는 추세인것 같아요.
- Reply-3: 이런 검증된 정보는 너무 유익하네요. 감사합니다.
- Reply-4: 먼저 좋은 정보 감사합니다 그러나 전에도 글로 언급드린 적있지만 **IB45점 만점에 40점이상되어야 국내 SKY대학에 갈수 있답니다**. 
작년 NLSC IB만점자가 설대 입학한것처럼 그러나 **IB세계 평균이 27점이고 40점**이면 Oxford University, Cambridge University등 세계유수의 대학을 갈수 있는데 과연 국내대학의 IB점수가 형평성 있을까요. 
대학부터 체질을 바꾸어야지 세계대학과 경쟁도 안되면서 참 아이러니합니다 마치 소나타 차량을 벤츠가격줘야 구입할수 있다는 비유와 같다봅니다
- Reply-5: 사이다 입니다. 그러나 안타까운 것은 우리가 바꿀수 없다는 것.. 대학이 바껴야 할텐데, 커트라인을 높이 잡아도 오겠다는 사람이 많으니 쉽지는 않을거 같습니다.
- Reply-6: IB 참 좋은 프로그램이지만 해외 고교재학시 중도 귀국자는 final까지 할 수 없으니 조금 불리한 듯 한데 국제학교로 편입하지 않고 sky 갈 수 있는 방법이 어떤 방법들이 있는 지 궁금하네요.

